
## Operator

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

# Section to describe components that needs to be installed
deployOperator: false
deployValidationWebhooks: false # Optional configuration.


clusterName: cluster.local

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: mongodb-enterprise-operator

  # Name of the deployment of the operator pod
  deployment_name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator and mongodb-enterprise-database images
  version: 1.7.2  

  # The Custom Resources that will be watched by the Operator. Needs to be changed if only some of the CRDs are installed
  watchedResources:
  - mongodb
  - opsmanagers
  - mongodbusers

  # When Operator is deployed globally add a list of namespaces to watch
  # watchNamespace:
  # - mongodb


dataBase:
  name: mdbshard
  type: ShardedCluster
  version: 4.4.0-ent
  opsManager:
    URL: "http://a4ca5e132cf524d7f844a2496475a791-1306499266.eu-west-1.elb.amazonaws.com:8080"
    APIKey: "JYRQENZZ"
    APISecret: "06370a71-734a-4d8d-82fc-33af5d1b2562"
    orgid: "5f7df975665e2f03a9daa6f6"  
  
  configServer:
    count: 3
    resources: 
      limits:
        cpu: 0.5
        memory: 600M
      requests:
        cpu: 1
        memory: 400M
  mongos:
    count: 2
    perShardCount: 2
    resources: 
      limits:
        cpu: 1
        memory: 200M
      requests:
        cpu: 0.5
        memory: 100M
  shard:
    count: 2
    resources: 
      limits:
        cpu: 2
        memory: 1.5G
      requests:
        cpu: 1
        memory: 1G

registry:
  # Redhat repository is registry.connect.redhat.com/mongod
  
  operator:
    Image: quay.io/mongodb/mongodb-enterprise-operator
    Tag: 1.7.1

  database:
    Image: quay.io/mongodb/mongodb-enterprise-database:1.7.1

  opsManager:
    Image: quay.io/mongodb/mongodb-enterprise-ops-manager

  initOpsManager:
    Image: quay.io/mongodbmongodb-enterprise-init-ops-manager
    Tag: 1.0.1

  appDb:
    Image: quay.io/mongodb/mongodb-enterprise-appdb

  initAppDb:
    Image: quay.io/mongodb/mongodb-enterprise-init-appdb
    Tag: 1.0.2

  imagePullSecrets:
  # TODO: specify for each image and move there?
  pullPolicy: Always
  # Specify if images are pulled from private registry

# Set this to true if the operator will require Kubernetes CA
# infrastructure to generate TLS certificates.
needsCAInfrastructure: true

# Set this to false to disable subresource utilization
# It might be required on some versions of Openshift
subresourceEnabled: true
